name: gooner_app_pro
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3
  json_annotation: ^4.9.0
  provider: ^6.1.5+1
  http: ^1.5.0
  video_player: ^2.10.0
  path_provider: ^2.1.5
  open_filex: ^4.7.0
  file_picker: ^10.3.3

  ## iOS specific libraries ##
  media_kit_video: ^1.3.1
  media_kit: ^1.2.1
  media_kit_libs_video: ^1.0.7
  share_plus: ^12.0.1
  url_launcher: ^6.3.2
  flutter_widget_from_html_core: ^0.17.0
  
  just_audio: ^0.10.5
  just_audio_background: ^0.0.1-beta.17
  audio_service: ^0.18.18
  audio_session: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.10.0
  json_serializable: ^6.11.1
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
